# Generated by Django 5.0.6 on 2024-06-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='family',
        ),
        migrations.AddField(
            model_name='person',
            name='family',
            field=models.ManyToManyField(to='todos.family'),
        ),
    ]
